# Generated by Django 3.2.9 on 2021-12-14 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AreYouIdol', '0002_auto_20211214_0515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
    ]
