# Generated by Django 3.2.9 on 2021-12-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AreYouIdol', '0003_delete_face'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreYouIdol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
