# Generated by Django 3.2.9 on 2021-12-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreYouIdol', '0004_areyouidol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfile', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='AreYouIdol',
        ),
    ]
