# Generated by Django 3.2.9 on 2021-12-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreYouIdol', '0006_auto_20211214_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
