# Generated by Django 3.2.9 on 2021-12-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AreYouIdol', '0008_alter_upload_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
